config/routes.rb
Rails.application.routes.draw do
  root :to => "articles#index"
  resources :articles do
    resources :comments
  end
  resources :users
  resource :session, :only => [:new,:create, :destroy]
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :body
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  
  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 }
  validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?
 
  has_one :profile
  
  before_save :encrypt_new_password
 
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user
  end
 
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
 
  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end
 
    def password_required?
      hashed_password.blank? || password.present?
    end
 
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected
  # Returns the currently logged in user or nil if there isn't one
  def current_user
  return unless session[:user_id]
  @current_user ||= User.find_by_id(session[:user_id])
  end
  # Make current_user available in templates as a helper
  helper_method :current_user
  # Filter method to enforce a login requirement
  # Apply as a before_action on any controller you want to protect
  def authenticate
  logged_in? || access_denied
  end
  # Predicate method to test for a logged in user
  def logged_in?
  current_user.is_a? User
  end
  # Make logged_in? available in templates as a helper
  helper_method :logged_in?
  def access_denied
    redirect_to login_path, notice: "Please log in to continue"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :location, :excerpt, :body, :published_at)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_article
 
 def create
 @comment = @article.comments.new(comment_params)
 if @comment.save
 redirect_to @article, notice: 'Thanks for your comment'
 else
 redirect_to @article, alert: 'Unable to add comment'
 end
 end
 
 def destroy
 @comment = @article.comments.find(params[:id])
 @comment.destroy
 redirect_to @article, notice: 'Comment Deleted'
 end
 
 private
 def load_article
 @article = Article.find(params[:article_id])
 end
 
 def comment_params
 params.require(:comment).permit(:name, :email, :body)
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
   if user = User.authenticate(params[:email], params[:password])
   session[:user_id] = user.id
   redirect_to root_path, :notice => "Logged in successfully"
   else
   flash.now[:alert] = "Invalid login/password combination"
   render :action => 'new'
   end
   end
   def destroy
    reset_session
    redirect_to root_path, :notice => "You successfully logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
 
  def new
    @user = User.new
  end
 
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to articles_path, notice: 'User successfully added.'
    else
      render action: :new
      end
  end 
 def edit
 end
 
 def update
 if @user.update(user_params)
 redirect_to articles_path, notice: 'Updated user information successfully.'
 else
 render action: 'edit'
 end
 end
 
 private
 def set_user
 @user = User.find(params[:id])
 end
 
 def user_params
 params.require(:user).permit(:email, :password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br>
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Excerpt</th>
      <th>Body</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.location %></td>
        <td><%= article.excerpt %></td>
        <td><%= article.body %></td>
        <td><%= article.published_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<% if session:user_id %>
 <% session:user_id%>
<% end%>
<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render @article %>
 
<h3>Comments</h3>
<div id="comments">
  <%= render @article.comments %>
</div>
 
<%= render :file => 'comments/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class="field">
 <%= f.label :email %><br />
 <%= f.text_field :email %>
 </div>
 <div class="field">
 <%= f.label :password %><br />
 <%= f.password_field :password %>
 </div>
 <div class="field">
 <%= f.label :password_confirmation %><br />
 <%= f.password_field :password_confirmation %>
 </div>
 <div class="actions">
 <%= f.submit %>
 </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>